openapi: 3.0.1
info:
  title: Cache (Dache) API
  description: This is used by the Edge servers to access features and environments quickly.
  version: "1.1.1"
paths:
  /environment/{eId}/{serviceAccountKey}:
    parameters:
      - name: eId
        description: "id of environment"
        in: path
        schema:
          type: string
          format: uuid
      - name: serviceAccountKey
        description: "serviceAccountKey of service account"
        in: path
        schema:
          type: string
    get:
      operationId: getApiKeyDetails
      tags:
        - DachaApiKeyService
      responses:
        200:
          description: "All feature values for this environment"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DachaKeyDetailsResponse"
        404:
          description: "No such environment/account combo has read access"
  /environment/{eId}/{serviceAccountKey}/permissions/{featureKey}:
    parameters:
      - name: eId
        description: "id of environment"
        in: path
        schema:
          type: string
          format: uuid
      - name: serviceAccountKey
        description: "id of service account"
        in: path
        schema:
          type: string
      - name: featureKey
        in: path
        description: "The key that we want"
        schema:
          type: string
    get:
      operationId: getApiKeyPermissions
      tags:
        - DachaApiKeyService
      responses:
        200:
          description: "All permissions and feature values for this environment"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DachaPermissionResponse"
        404:
          description: "No such environment/account combo has read access"
  /environment/{eId}/structure:
    parameters:
      - name: eId
        description: "id of environment"
        in: path
        schema:
          type: string
          format: uuid
    get:
      operationId: getEnvironmentStructure
      tags:
        - DachaEnvironmentService
      responses:
        200:
          description: "The parent structure for this environment"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DachaStructureResponse"
        404:
          description: "No such environment/account combo has read access"
components:
  schemas:
    CacheManagementMessage:
      required:
        - id
        - mit
        - requestType
        - cacheState
      properties:
        id:
          type: string
          format: uuid
        destId:
          description: "this allows one instance on the bus to communicate directly with another instance"
          type: string
          format: uuid
        requestType:
          $ref: "#/components/schemas/CacheRequestType"
        mit:
          description: "used only to negotiate master who is attempting to get data from MR"
          type: integer
          format: int64
        cacheState:
          $ref: "#/components/schemas/CacheState"
    CacheRequestType:
      type: string
      enum:
        - SEEKING_COMPLETE_CACHE
        - SEEKING_REFRESH
        - CLAIMING_MASTER
        - CACHE_REMOVED
        - CACHE_SOURCE
        - DUPLICATE_MIT
    CacheState:
      type: string
      enum:
        - NONE
        - REQUESTED
        - COMPLETE
    PublishAction:
      type: string
      description: "Indicates what type of update this is. If CREATE, it is a new record, if UPDATE it updates an existing one,
          if DELETE you should delete the record. If EMPTY then it indicates there are no records of this type and you shouldn't
          expect to see any further. EMPTY is used to indicate that the Master process is complete."
      enum:
        - CREATE
        - UPDATE
        - DELETE
        - EMPTY
    DachaStructureResponse:
      type: object
      required:
        - organizationId
        - portfolioId
        - applicationId
      properties:
        organizationId:
          x-basename: oId
          type: string
          format: uuid
        portfolioId:
          x-basename: pId
          type: string
          format: uuid
        applicationId:
          x-basename: aId
          type: string
          format: uuid
    EnvironmentCacheItem:
      properties:
        environment:
          $ref: "#/components/schemas/Environment"
        organizationId:
          x-basename: oId
          type: string
          format: uuid
        portfolioId:
          x-basename: pId
          type: string
          format: uuid
        applicationId:
          x-basename: aId
          type: string
          format: uuid
        featureValues:
          x-basename: fv
          type: array
          items:
            $ref: "#/components/schemas/FeatureValue"
        serviceAccounts:
          x-basename: sa
          type: array
          items:
            $ref: "#/components/schemas/ServiceAccount"
        action:
          $ref: "#/components/schemas/PublishAction"
        count:
          x-basename: c
          type: integer
    ServiceAccountCacheItem:
      properties:
        serviceAccount:
          $ref: "#/components/schemas/ServiceAccount"
        action:
          $ref: "#/components/schemas/PublishAction"
        count:
          type: integer
    DachaPermissionResponse:
      type: object
      required:
        - roles
        - feature
      properties:
        organizationId:
          x-basename: oId
          type: string
          format: uuid
        portfolioId:
          x-basename: pId
          type: string
          format: uuid
        applicationId:
          x-basename: aId
          type: string
          format: uuid
        serviceKeyId:
          description: "The actual service key id rather than the key"
          x-basename: sId
          type: string
          format: uuid
        roles:
          type: array
          items:
            $ref: "#/components/schemas/RoleType"
        feature:
          $ref: "#/components/schemas/DachaFeatureValueItem"
    DachaFeatureValueItem:
      required:
        - feature
        - value
      properties:
        feature:
          $ref: "#/components/schemas/Feature"
        value:
          $ref: "#/components/schemas/FeatureValue"
    FeatureValueCacheItem:
      required:
        - feature
        - value
        - environmentId
        - action
      properties:
        environmentId:
          description: "this needs to be passed because the feature value may be null"
          type: string
          format: uuid
        feature:
          $ref: "#/components/schemas/Feature"
        value:
          $ref: "#/components/schemas/FeatureValue"
        action:
          $ref: "#/components/schemas/PublishAction"
        strategies:
          type: array
          description: "A copy of the strategies that apply to this feature at this time."
          items:
            $ref: "#/components/schemas/RolloutStrategy"
    DachaKeyDetailsResponse:
      properties:
        etag:
          x-basename: etag
          type: string
        organizationId:
          x-basename: oId
          type: string
          format: uuid
        portfolioId:
          x-basename: pId
          type: string
          format: uuid
        applicationId:
          x-basename: aId
          type: string
          format: uuid
        serviceKeyId:
          description: "The actual service key id rather than the key"
          x-basename: sId
          type: string
          format: uuid
        features:
          type: array
          items:
            $ref: "#/components/schemas/FeatureValueCacheItem"
