steps:
  - name: 'maven:3.6.3-jdk-11'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - cd backend && mvn --no-transfer-progress install -f pom-first.xml && cd .. && mvn -T4C --no-transfer-progress install

