steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - kms
      - decrypt
      - --ciphertext-file=id_rsa.enc
      - --plaintext-file=/root/.ssh/id_rsa
      - --location=global
      - --keyring=featurehub-keyring
      - --key=featurehub-key
    volumes:
      - name: 'ssh'
        path: /root/.ssh
  # Set up git with key and domain.
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        chmod 600 /root/.ssh/id_rsa
        cat <<EOF >/root/.ssh/config
        Hostname gitlab.com
        IdentityFile /root/.ssh/id_rsa
        EOF
        mv known_hosts /root/.ssh/known_hosts
    volumes:
      - name: 'ssh'
        path: /root/.ssh

  - name: 'gcr.io/cloud-builders/git'
    args:
      - clone
      - git@gitlab.com:feature-mesh/feature-mesh.git
    volumes:
      - name: 'ssh'
        path: /root/.ssh
  # Use git clone.
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - cd feature-mesh && git checkout gcpbuild
    volumes:
      - name: 'ssh'
        path: /root/.ssh
  # Uses the Cloud Builder Git image since it is cached.
  # Links the Docker config to /root/.docker/config.json so Jib picks it up.
      # Note that this is only a temporary workaround.
      # See https://github.com/GoogleContainerTools/jib/pull/1479.

  # just confirm we are where we think we are
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - ls -la feature-mesh > log.txt
    volumes:
      - name: 'ssh'
        path: /root/.ssh

  - name: 'gcr.io/featurehub/basemvn:1.1'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - chmod u+x cloud-maven-build.sh && sh cloud-maven-build.sh

artifacts:
  objects:
    location: 'gs://featurehub_cloudbuild/'
    paths: ['log.txt']

#  - name: build and install tiles
#  - name: build and install all other artifacts (including docker images), push images to gcp
#  - name: build deploy container
#  - name: run up deploy container
#  - name: run e2e tests in dart container


