steps:
  - name: 'gcr.io/cloud-builders/kubectl'
    env:
      - CLOUDSDK_COMPUTE_ZONE=us-east1-b
      - CLOUDSDK_CONTAINER_CLUSTER=featurehub-dev
      - ENV=ci
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        chmod u+x delete-deploy-container.sh | sh delete-deploy-container.sh
  - name: 'gcr.io/cloud-builders/kubectl'
    env:
      - CLOUDSDK_COMPUTE_ZONE=us-east1-b
      - CLOUDSDK_CONTAINER_CLUSTER=featurehub-dev
      - ENV=ci
      - BUILD_TAG=1.7
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        chmod u+x run-and-wait-for-deploy.sh | sh run-and-wait-for-deploy.sh
