name: e2e_tests
description: An app built using Flutter for web

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  rxdart: ^0.26.0
  ogurets: ^4.0.0
  mrapi:
    path: ../admin-frontend/app_mr_layer
  openapi_dart_common: ^4.0.0
  collection: ^1.15.0
#  featurehub_client_sdk:
#    path: "../sdks/dart/client-dart-sdk"
dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8

