name: e2e_tests
description: An app built using Flutter for web

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  rxdart: ^0.26.0
#  ogurets: ^3.2.0
  ogurets:
    path: /Users/richard/projects/dart/ogurets
  mrapi:
    path: ../admin-frontend/app_mr_layer
  openapi_dart_common:
    path: '/Users/richard/projects/dart/openapi_dart_common'
  collection: ^1.15.0
#  featurehub_client_sdk:
#    path: "../sdks/dart/client-dart-sdk"
dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8

