name: mrapi
version: 1.0.0
description: OpenAPI API client
homepage: homepage
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  dio: '4.0.0-prev3'
  openapi_dart_common:
    path: '/Users/richard/projects/dart/openapi_dart_common'
  collection: '^1.15.0'
dev_dependencies:
  test: ^1.3.0
