name: mrapi
version: 1.0.0
description: OpenAPI API client
homepage: homepage

environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  dio: '4.0.0'
  openapi_dart_common: ^4.0.0
  collection: '^1.15.0'
dev_dependencies:
  test: ^1.3.0
# bought to you by the folks from FeatureHub https://featurehub.io
